# Generated by Django 6.0.4 on 2026-05-06 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('target_amount', models.FloatField()),
                ('current_amount', models.FloatField(default=0)),
                ('deadline', models.DateField()),
            ],
        ),
    ]
